#!/usr/bin/env bash
# Compile the RV32I guest binary and convert it to a C header.
# Requires: riscv64-elf-gcc (or riscv32-unknown-elf-gcc) on PATH.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GUEST_DIR="$SCRIPT_DIR/guest"
OUT_DIR="$SCRIPT_DIR/main"
OUT_BIN="$GUEST_DIR/hello.bin"
OUT_ELF="$GUEST_DIR/hello.elf"
OUT_HDR="$OUT_DIR/guest_bin.h"

# Prefer riscv64-elf-gcc if available, fall back to riscv32-unknown-elf-gcc
if command -v riscv64-elf-gcc &>/dev/null; then
    CC=riscv64-elf-gcc
    OBJCOPY=riscv64-elf-objcopy
elif command -v riscv64-unknown-elf-gcc &>/dev/null; then
    CC=riscv64-unknown-elf-gcc
    OBJCOPY=riscv64-unknown-elf-objcopy
elif command -v riscv32-unknown-elf-gcc &>/dev/null; then
    CC=riscv32-unknown-elf-gcc
    OBJCOPY=riscv32-unknown-elf-objcopy
else
    echo "ERROR: no RISC-V GCC found. Install via: brew install riscv-tools" >&2
    exit 1
fi

echo "Using compiler: $CC"

$CC \
    -march=rv32i \
    -mabi=ilp32 \
    -nostdlib \
    -nostartfiles \
    -ffreestanding \
    -Os \
    -Wall \
    -T "$GUEST_DIR/link.ld" \
    -o "$OUT_ELF" \
    "$GUEST_DIR/hello.c" \
    -lgcc

$OBJCOPY -O binary "$OUT_ELF" "$OUT_BIN"

BIN_SIZE=$(wc -c < "$OUT_BIN")
echo "Guest ELF: $OUT_ELF"
echo "Guest binary: $OUT_BIN ($BIN_SIZE bytes)"

# ---- Generate C header from the binary ----
{
    echo "#pragma once"
    echo "#include <stddef.h>"
    echo ""
    echo "/* Auto-generated by build_guest.sh — do not edit */"
    echo "static const unsigned char guest_bin[] = {"
    xxd -i < "$OUT_BIN" | sed 's/^/    /'
    echo "};"
    echo ""
    echo "static const size_t guest_bin_len = sizeof(guest_bin);"
} > "$OUT_HDR"

echo "Header written: $OUT_HDR"
